version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: our_database
      POSTGRES_USER: our_user
    ports:
      - "5433:5432"


  web-app:
    build: .
    restart: always
#    env_file: .env
    environment:
      DB_HOST: db
      DB_NAME: our_database
      DB_USER: our_user
      DB_PASSWORD: postgres
    volumes:
      - ./library:/library
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: my-password

      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - "8081:8081"




volumes:
  library:








